-- MySQL Script generated by MySQL Workbench
-- Thu Nov 20 10:43:22 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema concessionaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema concessionaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concessionaria` DEFAULT CHARACTER SET utf8 ;
USE `concessionaria` ;

-- -----------------------------------------------------
-- Table `concessionaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `cpf_cliente` VARCHAR(11) NULL,
  `telefone_cliente` VARCHAR(20) NULL,
  `email_cliente` VARCHAR(100) NULL,
  `endereco_cliente` VARCHAR(100) NULL,
  `dt_nasc_cliente` DATE NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(100) NOT NULL,
  `telefone_funcionario` VARCHAR(20) NULL,
  `email_funcionario` VARCHAR(100) NULL,
  PRIMARY KEY (`idfuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`marca` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `nome_marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`modelo` (
  `idmodelo` INT NOT NULL AUTO_INCREMENT,
  `nome_modelo` VARCHAR(100) NOT NULL,
  `cor_modelo` VARCHAR(100) NULL,
  `ano_modelo` YEAR NULL,
  `tipo_modelo` VARCHAR(100) NULL,
  `marca_idmarca` INT NOT NULL,
  PRIMARY KEY (`idmodelo`, `marca_idmarca`),
  INDEX `fk_modelo_marca1_idx` (`marca_idmarca` ASC) ,
  CONSTRAINT `fk_modelo_marca1`
    FOREIGN KEY (`marca_idmarca`)
    REFERENCES `concessionaria`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `data_venda` DATE NULL,
  `valor_venda` DECIMAL(10,2) NULL,
  `funcionario_idfuncionario` INT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  `modelo_idmodelo` INT NOT NULL,
  PRIMARY KEY (`idvenda`, `funcionario_idfuncionario`, `modelo_idmodelo`),
  INDEX `fk_venda_funcionario_idx` (`funcionario_idfuncionario` ASC) ,
  INDEX `fk_venda_cliente1_idx` (`cliente_idcliente` ASC) ,
  INDEX `fk_venda_modelo1_idx` (`modelo_idmodelo` ASC) ,
  CONSTRAINT `fk_venda_funcionario`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `concessionaria`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `concessionaria`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_modelo1`
    FOREIGN KEY (`modelo_idmodelo`)
    REFERENCES `concessionaria`.`modelo` (`idmodelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
